//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.13 at 11:23:52 PM PDT 
//


package com.tutor.agent.periodicelements;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PeriodicElement">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AtomicNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Element" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Symbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AtomicWeight" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Period" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Group" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Phase" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="MostStableCrystal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="IonicRadius" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AtomicRadius" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Electronegativity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="FirstIonizationPotential" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Density" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="MeltingPointK" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="BoilingPointK" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Isotopes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Discoverer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="YearofDiscovery" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SpecificHeatCapacity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ElectronConfiguration" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DisplayRow" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DisplayColumn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "periodicElement"
})
@XmlRootElement(name = "PeriodicElements")
public class PeriodicElements {

    @XmlElement(name = "PeriodicElement", required = true)
    protected PeriodicElements.PeriodicElement periodicElement;

    /**
     * Gets the value of the periodicElement property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodicElements.PeriodicElement }
     *     
     */
    public PeriodicElements.PeriodicElement getPeriodicElement() {
        return periodicElement;
    }

    /**
     * Sets the value of the periodicElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodicElements.PeriodicElement }
     *     
     */
    public void setPeriodicElement(PeriodicElements.PeriodicElement value) {
        this.periodicElement = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AtomicNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Element" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Symbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AtomicWeight" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Period" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Group" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Phase" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="MostStableCrystal" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="IonicRadius" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AtomicRadius" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Electronegativity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="FirstIonizationPotential" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Density" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="MeltingPointK" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="BoilingPointK" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Isotopes" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Discoverer" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="YearofDiscovery" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SpecificHeatCapacity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ElectronConfiguration" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DisplayRow" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DisplayColumn" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "atomicNumber",
        "element",
        "symbol",
        "atomicWeight",
        "period",
        "group",
        "phase",
        "mostStableCrystal",
        "type",
        "ionicRadius",
        "atomicRadius",
        "electronegativity",
        "firstIonizationPotential",
        "density",
        "meltingPointK",
        "boilingPointK",
        "isotopes",
        "discoverer",
        "yearofDiscovery",
        "specificHeatCapacity",
        "electronConfiguration",
        "displayRow",
        "displayColumn"
    })
    public static class PeriodicElement {

        @XmlElement(name = "AtomicNumber", required = true)
        protected String atomicNumber;
        @XmlElement(name = "Element", required = true)
        protected String element;
        @XmlElement(name = "Symbol", required = true)
        protected String symbol;
        @XmlElement(name = "AtomicWeight", required = true)
        protected String atomicWeight;
        @XmlElement(name = "Period", required = true)
        protected String period;
        @XmlElement(name = "Group", required = true)
        protected String group;
        @XmlElement(name = "Phase", required = true)
        protected String phase;
        @XmlElement(name = "MostStableCrystal", required = true)
        protected String mostStableCrystal;
        @XmlElement(name = "Type", required = true)
        protected String type;
        @XmlElement(name = "IonicRadius", required = true)
        protected String ionicRadius;
        @XmlElement(name = "AtomicRadius", required = true)
        protected String atomicRadius;
        @XmlElement(name = "Electronegativity", required = true)
        protected String electronegativity;
        @XmlElement(name = "FirstIonizationPotential", required = true)
        protected String firstIonizationPotential;
        @XmlElement(name = "Density", required = true)
        protected String density;
        @XmlElement(name = "MeltingPointK", required = true)
        protected String meltingPointK;
        @XmlElement(name = "BoilingPointK", required = true)
        protected String boilingPointK;
        @XmlElement(name = "Isotopes", required = true)
        protected String isotopes;
        @XmlElement(name = "Discoverer", required = true)
        protected String discoverer;
        @XmlElement(name = "YearofDiscovery", required = true)
        protected String yearofDiscovery;
        @XmlElement(name = "SpecificHeatCapacity", required = true)
        protected String specificHeatCapacity;
        @XmlElement(name = "ElectronConfiguration", required = true)
        protected String electronConfiguration;
        @XmlElement(name = "DisplayRow", required = true)
        protected String displayRow;
        @XmlElement(name = "DisplayColumn", required = true)
        protected String displayColumn;

        /**
         * Gets the value of the atomicNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAtomicNumber() {
            return atomicNumber;
        }

        /**
         * Sets the value of the atomicNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAtomicNumber(String value) {
            this.atomicNumber = value;
        }

        /**
         * Gets the value of the element property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getElement() {
            return element;
        }

        /**
         * Sets the value of the element property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setElement(String value) {
            this.element = value;
        }

        /**
         * Gets the value of the symbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSymbol() {
            return symbol;
        }

        /**
         * Sets the value of the symbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSymbol(String value) {
            this.symbol = value;
        }

        /**
         * Gets the value of the atomicWeight property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAtomicWeight() {
            return atomicWeight;
        }

        /**
         * Sets the value of the atomicWeight property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAtomicWeight(String value) {
            this.atomicWeight = value;
        }

        /**
         * Gets the value of the period property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPeriod() {
            return period;
        }

        /**
         * Sets the value of the period property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPeriod(String value) {
            this.period = value;
        }

        /**
         * Gets the value of the group property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGroup() {
            return group;
        }

        /**
         * Sets the value of the group property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGroup(String value) {
            this.group = value;
        }

        /**
         * Gets the value of the phase property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPhase() {
            return phase;
        }

        /**
         * Sets the value of the phase property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPhase(String value) {
            this.phase = value;
        }

        /**
         * Gets the value of the mostStableCrystal property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMostStableCrystal() {
            return mostStableCrystal;
        }

        /**
         * Sets the value of the mostStableCrystal property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMostStableCrystal(String value) {
            this.mostStableCrystal = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the ionicRadius property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIonicRadius() {
            return ionicRadius;
        }

        /**
         * Sets the value of the ionicRadius property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIonicRadius(String value) {
            this.ionicRadius = value;
        }

        /**
         * Gets the value of the atomicRadius property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAtomicRadius() {
            return atomicRadius;
        }

        /**
         * Sets the value of the atomicRadius property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAtomicRadius(String value) {
            this.atomicRadius = value;
        }

        /**
         * Gets the value of the electronegativity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getElectronegativity() {
            return electronegativity;
        }

        /**
         * Sets the value of the electronegativity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setElectronegativity(String value) {
            this.electronegativity = value;
        }

        /**
         * Gets the value of the firstIonizationPotential property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirstIonizationPotential() {
            return firstIonizationPotential;
        }

        /**
         * Sets the value of the firstIonizationPotential property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirstIonizationPotential(String value) {
            this.firstIonizationPotential = value;
        }

        /**
         * Gets the value of the density property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDensity() {
            return density;
        }

        /**
         * Sets the value of the density property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDensity(String value) {
            this.density = value;
        }

        /**
         * Gets the value of the meltingPointK property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMeltingPointK() {
            return meltingPointK;
        }

        /**
         * Sets the value of the meltingPointK property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMeltingPointK(String value) {
            this.meltingPointK = value;
        }

        /**
         * Gets the value of the boilingPointK property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBoilingPointK() {
            return boilingPointK;
        }

        /**
         * Sets the value of the boilingPointK property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBoilingPointK(String value) {
            this.boilingPointK = value;
        }

        /**
         * Gets the value of the isotopes property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsotopes() {
            return isotopes;
        }

        /**
         * Sets the value of the isotopes property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsotopes(String value) {
            this.isotopes = value;
        }

        /**
         * Gets the value of the discoverer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDiscoverer() {
            return discoverer;
        }

        /**
         * Sets the value of the discoverer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDiscoverer(String value) {
            this.discoverer = value;
        }

        /**
         * Gets the value of the yearofDiscovery property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getYearofDiscovery() {
            return yearofDiscovery;
        }

        /**
         * Sets the value of the yearofDiscovery property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setYearofDiscovery(String value) {
            this.yearofDiscovery = value;
        }

        /**
         * Gets the value of the specificHeatCapacity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSpecificHeatCapacity() {
            return specificHeatCapacity;
        }

        /**
         * Sets the value of the specificHeatCapacity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSpecificHeatCapacity(String value) {
            this.specificHeatCapacity = value;
        }

        /**
         * Gets the value of the electronConfiguration property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getElectronConfiguration() {
            return electronConfiguration;
        }

        /**
         * Sets the value of the electronConfiguration property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setElectronConfiguration(String value) {
            this.electronConfiguration = value;
        }

        /**
         * Gets the value of the displayRow property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDisplayRow() {
            return displayRow;
        }

        /**
         * Sets the value of the displayRow property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDisplayRow(String value) {
            this.displayRow = value;
        }

        /**
         * Gets the value of the displayColumn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDisplayColumn() {
            return displayColumn;
        }

        /**
         * Sets the value of the displayColumn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDisplayColumn(String value) {
            this.displayColumn = value;
        }

    }

}
